# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zobrero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='email',
        ),
    ]
