# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('zobrero', '0002_auto_20180405_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('receiver', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='WhatDoYouDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zobrero.Employee')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zobrero.Talent')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1920, max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='elon@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
