# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zobrero', '0003_auto_20180406_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='what_do_you_do',
        ),
    ]
