# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zobrero', '0006_talent_adjective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.Charfield(default=0, max_length=11),
        ),
    ]
