# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-21 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zobrero', '0009_auto_20180719_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messenger',
            old_name='ehaggler',
            new_name='chat',
        ),
    ]
